# Generated by Django 3.1.3 on 2020-12-07 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20201207_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token',
        ),
        migrations.AddField(
            model_name='token',
            name='token',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.user'),
        ),
    ]
