# Generated by Django 3.1.3 on 2021-01-06 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_auto_20201207_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('params', models.CharField(max_length=10000)),
                ('method', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fuzz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('fuzz_type', models.IntegerField(default=0)),
                ('fuzz_content', models.CharField(max_length=10000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_fuzz', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('extend', models.IntegerField(default=0)),
                ('task_type', models.IntegerField(default=0)),
                ('suite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.suite')),
            ],
        ),
        migrations.CreateModel(
            name='SuiteSetCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.IntegerField(null=True)),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.suite')),
            ],
        ),
        migrations.CreateModel(
            name='ReportItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('protocol', models.CharField(max_length=10)),
                ('method', models.CharField(max_length=10)),
                ('params', models.CharField(max_length=1000)),
                ('hope', models.CharField(max_length=100)),
                ('sum_time', models.CharField(max_length=50)),
                ('fact', models.CharField(max_length=10000)),
                ('result', models.IntegerField(default=0)),
                ('code', models.IntegerField(default=0)),
                ('task', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.task')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.CharField(max_length=100)),
                ('sum_time', models.CharField(max_length=10)),
                ('passed', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('no_check', models.IntegerField(default=0)),
                ('log', models.CharField(max_length=100, null=True)),
                ('report_path', models.CharField(max_length=100)),
                ('task', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.task')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('protocol', models.CharField(max_length=10)),
                ('method', models.CharField(max_length=10)),
                ('params', models.CharField(max_length=1000)),
                ('hope', models.CharField(max_length=100, null=True)),
                ('suite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.suite')),
            ],
        ),
    ]
