# Generated by Django 3.1.3 on 2021-01-17 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_apilogin_case_fuzz_report_reportitem_suite_suitesetcase_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='extend',
            new_name='task_state',
        ),
        migrations.AlterField(
            model_name='task',
            name='suite',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.suite'),
        ),
    ]
