# Generated by Django 3.1.3 on 2021-01-17 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_auto_20210117_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportitem',
            name='code',
        ),
        migrations.RemoveField(
            model_name='reportitem',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='suite',
        ),
        migrations.AddField(
            model_name='reportitem',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.report'),
        ),
    ]
