# Generated by Django 3.1.3 on 2021-01-20 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_auto_20210117_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='suite',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.suite'),
        ),
    ]
