# Generated by Django 3.1.3 on 2021-01-31 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_auto_20210124_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuzz',
            name='hope',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='hope',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
