# Generated by Django 3.1.3 on 2021-01-31 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_auto_20210131_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='hope',
        ),
    ]
