# Generated by Django 3.1.3 on 2021-01-31 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_remove_case_hope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fuzz',
            name='hope',
        ),
        migrations.AddField(
            model_name='case',
            name='hope',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
