# Generated by Django 3.1.3 on 2021-01-31 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0013_auto_20210131_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
