# Generated by Django 3.1.3 on 2022-03-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0014_task_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sum_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
